# BEGIN: 1d2f3g4h5j6k
site_name: Enterprise AI Group 2

# END: 1d2f3g4h5j6k
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
