channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=22.3.1
- pip:
  - mlflow==2.4
  - importlib-metadata==6.0.1
  - lz4==3.1.3
  - numpy==1.22.4
  - pandas==1.5.3
  - psutil==5.9.0
  - scikit-learn==1.2.1
  - scipy==1.8.1
  - typing-extensions==4.4.0
  - xgboost==1.7.5
name: mlflow-env
