artifact_location: file:///c:/Users/michi/enterpriseai_new_checkout/enterprise-ai-project/immowelt_price_guide/your_mlflow_server_uri/0
creation_time: 1689527527960
experiment_id: '0'
last_update_time: 1689527527960
lifecycle_stage: active
name: Default
