channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=23.1.2
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
